### ISSUE TITLE
Path error in boot.styl that prevents app.css from being built

### ISSUE THREAD

**Issue by bjstarosta** [DemocracyOS/democracyos#1133]
On node 5.0.0/npm 3.3.6 the latest pull throws when building app.css, thus causing the application to not have any css styling upon launch. During build this can be confirmed by seeing something similar to this in the logs:
```
Building...
[14:55:25] Using gulpfile /opt/democracyos/gulpfile.js
[14:55:25] Starting 'public'...
[14:55:25] Starting 'css:build'...
[14:55:25] Finished 'public' after 21 ms
[14:55:25] Starting 'js:build'...
[14:55:25] Starting 'assets'...
Potentially unhandled rejection [2] Error: no writecb in Transform class
    at afterTransform (/opt/democracyos/node_modules/gulp-stylus/node_modules/readable-stream/lib/_stream_transform.js:75:33)
    at TransformState.afterTransform (/opt/democracyos/node_modules/gulp-stylus/node_modules/readable-stream/lib/_stream_transform.js:59:12)
    at /opt/democracyos/node_modules/gulp-stylus/index.js:47:16
    at tryCatchReject (/opt/democracyos/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/opt/democracyos/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (/opt/democracyos/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (/opt/democracyos/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/opt/democracyos/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/opt/democracyos/node_modules/when/lib/Scheduler.js:27:9)
    at doNTCallback0 (node.js:428:9)
[14:55:31] Finished 'assets' after 5.99 s
[14:55:38] Finished 'js:build' after 14 s
Launching...
[14:55:40] Using gulpfile /opt/democracyos/gulpfile.js
[14:55:40] Starting 'serve'...
```
This error is not very descriptive, but it's caused by the css file concat function not being able to find all the css files to put together. The problem lies in lib/boot/boot.styl at line 4:
```
@import '../../node_modules/democracyos-datepicker/node_modules/democracyos-aurora/node_modules/democracyos-aurora-popover/node_modules/democracyos-aurora-tip/aurora-tip.css'
@import '../../node_modules/democracyos-tip/tip.css'
@import '../../node_modules/democracyos-datepicker/datepicker.css'
@import '../../node_modules/democracyos-datepicker/node_modules/democracyos-calendar/lib/calendar.css'
@import '../../node_modules/democracyos-datepicker/node_modules/democracyos-aurora/node_modules/democracyos-aurora-calendar/style.css'
@import '../../node_modules/democracyos-datepicker/node_modules/democracyos-aurora/node_modules/democracyos-aurora-popover/aurora-popover.css'
```
If I change the above lines to:
```
@import '../../node_modules/democracyos-aurora-tip/aurora-tip.css'
@import '../../node_modules/democracyos-tip/tip.css'
@import '../../node_modules/democracyos-datepicker/datepicker.css'
@import '../../node_modules/democracyos-calendar/lib/calendar.css'
@import '../../node_modules/democracyos-aurora-calendar/style.css'
@import '../../node_modules/democracyos-aurora-popover/aurora-popover.css'
```
app.css builds properly, and everything works as it should.

Submitting this as an issue, as I'm not sure whether simply updating the files won't cause the issue to appear in older npm versions.

**Comment by agustin107** [comment]
I tried reproduce that bug, with node 5.0.0 and npm 3.3.6, and i didn't get.

**Comment by mjlescano** [comment]
@bjstarosta on which OS?

**Comment by bjstarosta** [comment]
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.2 (jessie)
Release:	8.2
Codename:	jessie

**Comment by jfresco** [comment]
@bjstarosta Did you tried to switch the node version? I tried with 4.0.0, 4.2.2 and 5.0.0 and I can't reproduce the error in my OSX.
I did a little research and some people fixed it by switching the Node version.

**Comment by bjstarosta** [comment]
Tried on node 4.2.2/npm 2.14.7 and error doesn't occur. I guess it's related to npm version on certain OS?

**Comment by jfresco** [comment]
Could be. We currently support Node `4.x.x` because is the long term supported. Node 5 is cutting edge branch and can lead to unexpected behaviors.

**Comment by jfresco** [comment]
Now it's happening to me with Node 4.2.2 and npm 2.14.7 in Mac OSX. I'll try to debug it.

**Comment by jfresco** [comment]
Related: #1153

**Comment by jfresco** [comment]
Seems like an error trying to fetch `.css` files in `node_modules` that are dependencies of dependencies. `npm v3` now doesn't install nested deps, so the paths are different.
Therefore, `gulp` halts with this dark error.
