### ISSUE TITLE
Installation problems: Error: Cannot find module 'commander' 

### ISSUE THREAD

**Issue by dalareo** [DemocracyOS/democracyos#1149]
I get:

    module.js:340
    throw err;
          ^
    Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/user/Software/democracyos/bin/dos-install:11:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

when executing node ./bin/dos-install.
I need to install commander node module first, with npm install commander. Is this the normal behaviour??

I am using either Ubuntu 14.04 with node 12.07 and Debian Jessie with default packages from Debian repo.

**Comment by slifszyc** [comment]
Try updating `node` to `4.2.1`

**Comment by dalareo** [comment]
The same problem with node v5.0.1

**Comment by slifszyc** [comment]
Sorry I had not read your problem properly

Why are you trying to run that script? `node ./bin/dos-install`

That had to do with previous versions of DemocracyOS.

**Comment by dalareo** [comment]
I'm just following instructions here: http://docs.democracyos.org/install.html

node ./bin/dos-install --config

**Comment by slifszyc** [comment]
Please run `npm install` before running `node ./bin/dos-install --config`.

Or are you trying to run this code on production?

**Comment by robertclarkson** [comment]
Great! Thanks for the answer. This should be in the install docs

**Comment by madangopal918** [comment]
tiger@ubuntu:/usr/lib/node_modules/stf$ sudo stf local
module.js:471
throw err;
^

Error: Cannot find module 'commander'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object. (/usr/lib/node_modules/stf/lib/cli.js:4:15)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)

should we run stf local command inside stf folder or in home directory ? please help

**Comment by hanhuizhu** [comment]
remove node_moduel and  cnpm i

**Comment by azharuddin207** [comment]
what is the solution of this problem?
please give complete guidance

facing this error

express -h
internal/modules/cjs/loader.js:657
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/lib/nodejs/express-generator/bin/express:3:15)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)

**Comment by felipemeloo** [comment]
I have the same problem! How do you fix?
