### ISSUE TITLE
mongoose schema caster error on install

### ISSUE THREAD

**Issue by jskye** [DemocracyOS/democracyos#1318]
previously i was testing with an earlier release, but i switched back to current `master`.
trying to install, I get error:

```
/Users/jsky/votebird/node_modules/democracyos-db/node_modules/mongoose/lib/schema/array.js:58
    this.caster = new caster(null, castOptions);
                  ^

TypeError: caster is not a constructor
    at new SchemaArray (/Users/jsky/votebird/node_modules/democracyos-db/node_modules/mongoose/lib/schema/array.js:58:19)
    at Function.Schema.interpretAsType (/Users/juliusskye/votebird/node_modules/democracyos-db/node_modules/mongoose/lib/schema.js:350:12)
    at Schema.path (/Users/jsky/votebird/node_modules/democracyos-db/node_modules/mongoose/lib/schema.js:305:29)
    at Schema.add (/Users/jsky/votebird/node_modules/democracyos-db/node_modules/mongoose/lib/schema.js:217:12)
    at Schema.add (/Users/jsky/votebird/node_modules/democracyos-db/node_modules/mongoose/lib/schema.js:212:14)
    at new Schema (/Users/jsky/votebird/node_modules/democracyos-db/node_modules/mongoose/lib/schema.js:73:10)
    at NativeConnection.Connection.model (/Users/jsky/votebird/node_modules/democracyos-db/node_modules/mongoose/lib/connection.js:587:14)
    at initialize (/Users/jsky/votebird/lib/models/topic.js:414:15)
    at module.exports (/Users/jsky/votebird/lib/models/index.js:12:21)
    at Object.<anonymous> (/Users/jsky/votebird/lib/boot/index.js:35:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
```

Similar to [these](https://github.com/saintedlama/mongoose-version/issues/6)..
Apparently its [fixed](https://github.com/Automattic/mongoose/commit/c581a753efadaa256bb1d7e30d36c305a16bc2db) in latest mongoose, but not sure/if how to propogate to the db's mongoose or if schema needs fixing.

```
 npm list mongoose
democracyos@1.4.4 /Users/jsky/votebird
├─┬ democracyos-db@0.0.1
│ └── mongoose@3.8.24 
└── mongoose@4.6.3 
```

**Comment by jskye** [comment]
I think this happened when i was trying to update mongoose or npm or node and there was mismatched dependencies. 

After pulling the latest commit and reverting to those dependencies this no longer happened, but 
this other error returned,

```
Failed to load c++ bson extension, using pure JS version
/Users/juliusskye/votebird/node_modules/democracyos-db/node_modules/mongoose/lib/schema.js:362
    throw new TypeError('Undefined type at `' + path +
    ^
```

It seems familiar, but if i fixed it before, i cant recall how i did.
I also get [this bson error](https://github.com/DemocracyOS/democracyos/issues/1307) again, (but i dont really care about that for now, solong as i have a working dev env),

Im just trying to remember how to fix this current error. If anyone can help, much appreciated.

**Comment by jskye** [comment]
Ok. after dumping the node_modules and starting again i got rid of this error only to get another error that ive had before, but i forget how to fix also.

```
/Users/juliusskye/votebird/node_modules/agenda/node_modules/mongodb/lib/utils.js:97
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Proxy.create is not a function
    at module.exports (/Users/juliusskye/votebird/node_modules/mongojs/index.js:8:19)
    at connectToMongoDB (/Users/juliusskye/votebird/node_modules/democracyos-notifier/lib/db/index.js:9:12)
    at module.exports (/Users/juliusskye/votebird/node_modules/democracyos-notifier/lib/jobs/lib/comment-reply.js:10:8)
    at initEvent (/Users/juliusskye/votebird/node_modules/democracyos-notifier/lib/jobs/index.js:8:7)
    at /Users/juliusskye/votebird/node_modules/require-all/index.js:38:42
    at Array.forEach (native)
    at requireAll (/Users/juliusskye/votebird/node_modules/require-all/index.js:21:9)
    at initializeJobs (/Users/juliusskye/votebird/node_modules/democracyos-notifier/lib/jobs/index.js:5:3)
    at /Users/juliusskye/votebird/node_modules/democracyos-notifier/index.js:40:5
    at /Users/juliusskye/votebird/node_modules/agenda/lib/agenda.js:230:5

```

**Comment by mjlescano** [comment]
@jskye during this week I'll be updating `mongoose`, that should fix this errors :)

**Comment by mjlescano** [comment]
This should be fixed on `add-react` branch, that is going to be on `master` soon. Closing the issue.
