### ISSUE TITLE
Installation on Ubuntu

### ISSUE THREAD

**Issue by jpotts-IIL** [DemocracyOS/democracyos#1407]
I am having a problem getting DemocracyOS up and running on Ubuntu (16.04). I have the following installed:

- Node.js v6.10.2
- npm v3.10.10
- MongoDB  Shell Version v3.4.4

I can run all the make commands fine and can run `make run` fine. When I go to http://localhost:3000 I am presented with a login screen. On signing up and attempting to login I get the following error:

```
democracyos:db-api:forum No forum found with name undefined +3ms
/home/user/Documents/democracyos/lib/privileges/forum.js:39
    return forum.isOwner(user) || forum.hasRole(user, 'admin', 'collaborator', 'author')
                ^

TypeError: Cannot read property 'isOwner' of undefined
    at Object.canChangeTopics (/home/user/Documents/democracyos/lib/privileges/forum.js:39:17)
    at /home/user/Documents/democracyos/lib/middlewares/user/index.js:28:10
    at Query.<anonymous> (/home/user/Documents/democracyos/lib/db-api/forum.js:165:16)
    at /home/user/Documents/democracyos/node_modules/kareem/index.js:273:21
    at /home/user/Documents/democracyos/node_modules/kareem/index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

npm ERR! Linux 4.8.0-49-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! democracyos@2.2.3 start: `NODE_PATH=. node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the democracyos@2.2.3 start script 'NODE_PATH=. node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the democracyos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_PATH=. node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs democracyos
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls democracyos
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/Documents/democracyos/npm-debug.log
Makefile:14: recipe for target 'run' failed
make: *** [run] Error 1
```

I suspected this had something to do with the fact that the database had no data in it. I tried to load in some sample data following the guide here: https://github.com/DemocracyOS/democracyos/wiki/Load-fixtures but was confronted with another error when I run the command 'NODE_PATH=. node ./bin/dos-db load tag ./lib/fixtures/tags.json':

```
TypeError: Tag is not a constructor
    at Object.create (/home/user/Documents/democracyos/lib/db-api/tag.js:193:4)
    at /home/user/Documents/democracyos/bin/dos-db:45:34
    at Array.forEach (native)
    at /home/user/Documents/democracyos/bin/dos-db:44:12
    at /home/user/Documents/democracyos/node_modules/mongoose/lib/connection.js:292:19
    at open (/home/user/Documents/democracyos/node_modules/mongoose/lib/connection.js:576:17)
    at NativeConnection.Connection.onOpen (/home/user/Documents/democracyos/node_modules/mongoose/lib/connection.js:586:5)
    at /home/user/Documents/democracyos/node_modules/mongoose/lib/connection.js:546:11
    at /home/user/Documents/democracyos/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:71:5
    at /home/user/Documents/democracyos/node_modules/mongoose/node_modules/mongodb/lib/db.js:236:5
    at Server.connectHandler (/home/user/Documents/democracyos/node_modules/mongoose/node_modules/mongodb/lib/server.js:339:7)
    at Server.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at /home/user/Documents/democracyos/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:298:14
    at /home/user/Documents/democracyos/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:461:18
/home/user/Documents/democracyos/node_modules/mongoose/node_modules/mongodb/lib/server.js:342
      process.nextTick(function() { throw err; })
```

Do you have any suggestions about how I can fix this issue and get DemocracyOS up and running successfully?

**Comment by jpotts-IIL** [comment]
I was able to login by following the instructions on this page and creating an admin account: https://github.com/DemocracyOS/democracyos/wiki/Admin-module
