### ISSUE TITLE
Error when trying to load a topic with dos-db

### ISSUE THREAD

**Issue by LuisAlejandro** [DemocracyOS/democracyos#1424]
Hi everyone, i get this error when trying to load a topic:

```
app_1    | /usr/src/node_modules/mongoose/node_modules/mongodb/lib/server.js:267
app_1    |         process.nextTick(function() { throw err; })
app_1    |                                       ^
app_1    | 
app_1    | TypeError: api[model.toLowerCase(...)].create is not a function
app_1    |     at /usr/src/bin/dos-db:46:34
app_1    |     at Array.forEach (native)
app_1    |     at /usr/src/bin/dos-db:44:12
app_1    |     at /usr/src/node_modules/mongoose/lib/connection.js:292:19
app_1    |     at NativeConnection.Connection.error (/usr/src/node_modules/mongoose/lib/connection.js:510:12)
app_1    |     at /usr/src/node_modules/mongoose/lib/connection.js:541:15
app_1    |     at /usr/src/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:69:21
app_1    |     at /usr/src/node_modules/mongoose/node_modules/mongodb/lib/db.js:233:14
app_1    |     at Server.<anonymous> (/usr/src/node_modules/mongoose/node_modules/mongodb/lib/server.js:265:9)
app_1    |     at Server.g (events.js:292:16)
app_1    |     at emitOne (events.js:96:13)
app_1    |     at Server.emit (events.js:188:7)
app_1    |     at Pool.<anonymous> (/usr/src/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:327:21)
app_1    |     at emitOne (events.js:96:13)
app_1    |     at Pool.emit (events.js:188:7)
app_1    |     at Connection.<anonymous> (/usr/src/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:274:12)
```

The topic model doesn't seem to have a create function. Is this a known bug?

**Comment by LuisAlejandro** [comment]
Ah, this is the command I'm using (version 2.5.2)

```
./bin/dos-db load topic /usr/src/lib/fixtures/topics.json
```

**Comment by LuisAlejandro** [comment]
You seem to have removed the create function here:

https://github.com/DemocracyOS/democracyos/commit/5bbcfcc03d41a5c3170c87651b03a5babb75df1d

I don't know why, how is dos-db supposed to know how to create a model instance without using api-v2?

**Comment by franciclo** [comment]
Closing since we are not mantaining that script no more and will be deprecated soon. Sorry.
