### ISSUE TITLE
make packages fail

### ISSUE THREAD

**Issue by kpoman** [DemocracyOS/democracyos#1428]
Hello,
I am trying to install on an Ubuntu Server VM, and got this error while make packages:

4355 info lifecycle node-sass@4.5.3~install: Failed to exec install script
4356 verbose unlock done using /root/.npm/_locks/staging-a249b6e182e31a9a.lock for /home/kpoman/democracyos/democracyos/node_modules/.staging
4357 silly rollbackFailedOptional Starting
4358 silly rollbackFailedOptional Finishing
4359 silly runTopLevelLifecycles Starting
4360 silly runTopLevelLifecycles Finishing
4361 silly install printInstalled
4362 warn optional Skipping failed optional dependency /chokidar/fsevents:
4363 warn notsup Not compatible with your operating system or architecture: fsevents@1.1.2
4364 warn optional Skipping failed optional dependency /babel-cli/chokidar/fsevents:
4365 warn notsup Not compatible with your operating system or architecture: fsevents@1.1.2
4366 warn jadeify@4.6.0 requires a peer of browserify@>= 2.4.0 < 14 but none was installed.
4367 verbose stack Error: node-sass@4.5.3 install: `node scripts/install.js`
4367 verbose stack spawn ENOENT
4367 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
4367 verbose stack     at emitTwo (events.js:87:13)
4367 verbose stack     at ChildProcess.emit (events.js:172:7)
4367 verbose stack     at maybeClose (internal/child_process.js:821:16)
4367 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
4368 verbose pkgid node-sass@4.5.3
4369 verbose cwd /home/kpoman/democracyos/democracyos
4370 error Linux 4.4.0-62-generic
4371 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
4372 error node v4.2.6
4373 error npm  v3.5.2
4374 error file sh
4375 error code ELIFECYCLE
4376 error errno ENOENT
4377 error syscall spawn
4378 error node-sass@4.5.3 install: `node scripts/install.js`
4378 error spawn ENOENT
4379 error Failed at the node-sass@4.5.3 install script 'node scripts/install.js'.
4379 error Make sure you have the latest version of node.js and npm installed.
4379 error If you do, this is most likely a problem with the node-sass package,
4379 error not with npm itself.
4379 error Tell the author that this fails on your system:
4379 error     node scripts/install.js
4379 error You can get information on how to open an issue for this project with:
4379 error     npm bugs node-sass
4379 error Or if that isn't available, you can get their info via:
4379 error     npm owner ls node-sass
4379 error There is likely additional logging output above.
4380 verbose exit [ 1, true ]

**Comment by kpoman** [comment]
Apparently missing symlink. This fixed it:

ln -s /usr/bin/nodejs /usr/bin/node
