### ISSUE TITLE
Gulp bws throws error

### ISSUE THREAD

**Issue by sineau** [DemocracyOS/democracyos#1429]
I'm trying to use the `gulp bws`, but it throws an error as follows:

```
module.js:440
    throw err;
    ^

Error: Cannot find module 'lib/ext/entries'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/siina/Coding/democracyos/lib/build/index.js:13:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

```

I checked and the module in question is available. Any suggestions?

**Comment by sineau** [comment]
Hi again,
Here's the fix. In `lib/build/index.js` line 13 should change to:
`const extEntries = require('../ext/entries')`
