### ISSUE TITLE
Issue in starting democracyos first time from docker-compose

### ISSUE THREAD

**Issue by yurilaaziz** [DemocracyOS/democracyos#1460]
Hello 
I am running democracyos using docker-compose.yml 
I got  a db migration error 
```
democracyos:migrations Database migrations are up to date. +122ms
TypeError: Cannot set property 'mailer' of undefined
    at Mail (/usr/src/node_modules/nodemailer/lib/mailer/index.js:45:33)
    at Object.module.exports.createTransport (/usr/src/node_modules/nodemailer/lib/nodemailer.js:46:14)
    at Object.<anonymous> (/usr/src/node_modules/democracyos-notifier/lib/mailer/transporter.js:15:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/node_modules/democracyos-notifier/lib/mailer/index.js:3:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.init (/usr/src/node_modules/democracyos-notifier/index.js:25:5)
    at Object.start (/usr/src/node_modules/democracyos-notifier/index.js:57:19)
    at startNotificationsService (/usr/src/lib/server/index.js:35:65)
    at listen (/usr/src/lib/server/index.js:40:5)

```
 
By changing the nodemailer in (config/defaults.json) from 
```
  "nodemailer": {}
```
to

```
  "nodemailer": {
      "name": "The DemocracyOS Team",
      "email": "no-reply@democracyos.org",
      "service": "",
      "auth": {
        "user": "",
        "pass": ""
      }
    }
```

The server start but in a panic state, the page is refreshing and no way to access the site.

```
> 
> democracyos:utils Checking for logged in user +0ms
>   democracyos:utils User is not logged in. Path /user/me is restricted. +0ms
>   democracyos:jwt HTTP header x-access-token has no token. Moving on... +88ms
>   democracyos:l10n Inferring user locale from HTTP header accept-language: en-US,en;q=0.5 +0ms
>   democracyos:l10n Setting locale: en +1ms
>   democracyos:utils Checking for logged in user +0ms
>   democracyos:utils User is not logged in. Path /user/me is restricted. +0ms
>   democracyos:jwt HTTP header x-access-token has no token. Moving on... +59ms
>   democracyos:l10n Inferring user locale from HTTP header accept-language: en-US,en;q=0.5 +0ms
>   democracyos:l10n Setting locale: en +0ms
>   democracyos:db-api:forum Searching for forum with name undefined +0ms
>   democracyos:db-api:forum No forum found with name undefined +1ms
>   democracyos:jwt HTTP header x-access-token has no token. Moving on... +305ms
>   democracyos:l10n Inferring user locale from HTTP header accept-language: en-US,en;q=0.5 +0ms
>   democracyos:l10n Setting locale: en +1ms
>   democracyos:utils Checking for logged in user +0ms
>   democracyos:utils User is not logged in. Path /user/me is restricted. +0ms
>   democracyos:jwt HTTP header x-access-token has no token. Moving on... +103ms
>   democracyos:l10n Inferring user locale from HTTP header accept-language: en-US,en;q=0.5 +0ms
>   democracyos:l10n Setting locale: en +0ms
>   democracyos:utils Checking for logged in user +0ms
>   democracyos:utils User is not logged in. Path /user/me is restricted. +0ms
>   democracyos:jwt HTTP header x-access-token has no token. Moving on... +57ms
>   democracyos:l10n Inferring user locale from HTTP header accept-language: en-US,en;q=0.5 +0ms
>   democracyos:l10n Setting locale: en +0ms
```

**Comment by franciclo** [comment]
fixed in latest version, this was an issue in democracyos-notifier repo.
