### ISSUE TITLE
Install Fail

### ISSUE THREAD

**Issue by soodoenim** [DemocracyOS/democracyos#1480]
Can someone help me figure out what I should do from here? I checked, and node-sass is installed.

Installing dependencies...
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> node-sass@4.7.2 install /home/soodoenim/Desktop/democracyos-master/node_modules/node-sass
> node scripts/install.js

sh: 1: node: not found
democracyos@2.9.8 /home/soodoenim/Desktop/democracyos-master
├── UNMET PEER DEPENDENCY browserify@14.1.0
├─┬ gulp-sourcemaps@2.4.1
│ └─┬ css@2.2.1
│   └── source-map@0.1.43 
├─┬ jade@1.11.0
│ └─┬ transformers@2.1.0
│   └─┬ uglify-js@2.2.5
│     └── source-map@0.1.43 
├── UNMET PEER DEPENDENCY react@15.6.2
└─┬ stylus@0.54.5
  └── source-map@0.1.43 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN optional Skipping failed optional dependency /babel-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN jadeify@4.6.0 requires a peer of browserify@>= 2.4.0 < 14 but none was installed.
npm WARN react-paginate@5.0.0 requires a peer of react@^16.0.0 but none was installed.
npm ERR! Linux 4.13.0-26-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-sass@4.7.2 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@4.7.2 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/soodoenim/Desktop/democracyos-master/npm-debug.log
Makefile:22: recipe for target 'packages' failed
make: *** [packages] Error 1

**Comment by franciclo** [comment]
what version of node are you using? it should be 6.x
is that the output of doing `npm install` after cloning the proyect?

**Comment by srthorat** [comment]
@franciclo  On which OS this=> http://docs.democracyos.org/install.html installation steps will work without any efforts. I was trying on Ubuntu 16.04 sucked with installation, Facing multiple issues. One of them is below,

/home/democracyos/lib/models/forum/topics-attrs.js:5
    name: { type: String, maxlength: 32, minlength: 1, required: true },
    ^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/docker/demo/democracyos/lib/models/forum/index.js:7:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at models (/home/docker/demo/democracyos/lib/models/index.js:37:19)
    at Object.<anonymous> (/home/docker/demo/democracyos/lib/boot/index.js:32:22)

npm ERR! Linux 4.13.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! democracyos@2.11.4 start: `NODE_PATH=. node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the democracyos@2.11.4 start script 'NODE_PATH=. node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the democracyos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_PATH=. node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs democracyos
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls democracyos
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/docker/demo/democracyos/npm-debug.log
Makefile:14: recipe for target 'run' failed
make: *** [run] Error 1

**Comment by srthorat** [comment]
@soodoenim Are u able to install it successfully if Yes please share detailed steps.
